const sampleMeals = [
  // ==================== BREAKFAST MEALS ====================
  {
    name: "Greek Yogurt Protein Bowl",
    description:
      "Creamy Greek yogurt loaded with fresh berries, nuts, and honey for sustained energy",
    mealType: "breakfast",
    imageUrl:
      "https://images.unsplash.com/photo-1576021182217-7d005ef5bbc9?w=400&h=300&fit=crop",
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    ingredients: [
      { name: "Greek Yogurt", amount: 200, unit: "g" },
      { name: "Mixed Berries", amount: 100, unit: "g" },
      { name: "Almonds", amount: 30, unit: "g" },
      { name: "Chia Seeds", amount: 1, unit: "tbsp" },
      { name: "Honey", amount: 1, unit: "tbsp" },
    ],
    instructions: [
      "Scoop Greek yogurt into a bowl",
      "Top with mixed berries and almonds",
      "Sprinkle chia seeds and drizzle with honey",
      "Mix gently and enjoy immediately",
    ],
    nutrition: {
      calories: 320,
      protein: 28,
      carbohydrates: 35,
      fats: 12,
      fiber: 8,
      sugar: 22,
      sodium: 85,
    },
    dietaryTags: ["high-protein", "vegetarian", "gluten-free"],
    allergens: ["dairy", "nuts"],
    difficulty: "easy",
    isActive: true,
    averageRating: 4.7,
  },
  {
    name: "Avocado Toast with Poached Eggs",
    description:
      "Creamy avocado spread on whole grain toast topped with perfectly poached eggs",
    mealType: "breakfast",
    imageUrl:
      "https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=400&h=300&fit=crop",
    prepTime: 10,
    cookTime: 5,
    servings: 1,
    ingredients: [
      { name: "Whole Grain Bread", amount: 2, unit: "slice" },
      { name: "Avocado", amount: 1, unit: "piece" },
      { name: "Eggs", amount: 2, unit: "piece" },
      { name: "Lemon Juice", amount: 1, unit: "tsp" },
      { name: "Red Pepper Flakes", amount: 0.5, unit: "tsp" },
      { name: "Salt", amount: 0.25, unit: "tsp" },
    ],
    instructions: [
      "Toast bread until golden brown",
      "Mash avocado with lemon juice and salt",
      "Poach eggs in simmering water for 3-4 minutes",
      "Spread avocado on toast, top with poached eggs",
      "Sprinkle with red pepper flakes",
    ],
    nutrition: {
      calories: 380,
      protein: 20,
      carbohydrates: 28,
      fats: 22,
      fiber: 12,
      sugar: 3,
      sodium: 420,
    },
    dietaryTags: ["high-protein", "vegetarian", "high-fiber"],
    allergens: ["eggs", "wheat"],
    difficulty: "medium",
    isActive: true,
    averageRating: 4.5,
  },
  {
    name: "Protein Oatmeal with Berries",
    description:
      "Hearty oatmeal boosted with protein powder and fresh seasonal berries",
    mealType: "breakfast",
    imageUrl:
      "https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?w=400&h=300&fit=crop",
    prepTime: 5,
    cookTime: 10,
    servings: 1,
    ingredients: [
      { name: "Rolled Oats", amount: 50, unit: "g" },
      { name: "Vanilla Protein Powder", amount: 30, unit: "g" },
      { name: "Mixed Berries", amount: 100, unit: "g" },
      { name: "Almond Milk", amount: 200, unit: "ml" },
      { name: "Cinnamon", amount: 0.5, unit: "tsp" },
    ],
    instructions: [
      "Cook oats with almond milk for 8-10 minutes",
      "Stir in protein powder until smooth",
      "Top with fresh berries and cinnamon",
      "Serve warm",
    ],
    nutrition: {
      calories: 350,
      protein: 32,
      carbohydrates: 45,
      fats: 6,
      fiber: 9,
      sugar: 15,
      sodium: 180,
    },
    dietaryTags: ["high-protein", "vegetarian", "gluten-free"],
    allergens: [],
    difficulty: "easy",
    isActive: true,
    averageRating: 4.6,
  },

  // ==================== LUNCH MEALS ====================
  {
    name: "Grilled Chicken Quinoa Bowl",
    description:
      "Protein-packed bowl with grilled chicken, quinoa, and roasted vegetables",
    mealType: "lunch",
    imageUrl:
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop",
    prepTime: 15,
    cookTime: 20,
    servings: 1,
    ingredients: [
      { name: "Chicken Breast", amount: 150, unit: "g" },
      { name: "Quinoa", amount: 100, unit: "g" },
      { name: "Bell Peppers", amount: 1, unit: "piece" },
      { name: "Zucchini", amount: 0.5, unit: "piece" },
      { name: "Olive Oil", amount: 1, unit: "tbsp" },
      { name: "Lemon Juice", amount: 2, unit: "tbsp" },
    ],
    instructions: [
      "Cook quinoa according to package instructions",
      "Grill chicken breast until cooked through",
      "Roast vegetables with olive oil",
      "Combine all ingredients in a bowl",
      "Dress with lemon juice and herbs",
    ],
    nutrition: {
      calories: 420,
      protein: 38,
      carbohydrates: 45,
      fats: 12,
      fiber: 8,
      sugar: 6,
      sodium: 280,
    },
    dietaryTags: ["high-protein", "gluten-free", "balanced"],
    allergens: [],
    difficulty: "medium",
    isActive: true,
    averageRating: 4.8,
  },
  {
    name: "Mediterranean Chickpea Salad",
    description:
      "Fresh salad with chickpeas, cucumbers, tomatoes, and feta cheese",
    mealType: "lunch",
    imageUrl:
      "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop",
    prepTime: 15,
    cookTime: 0,
    servings: 1,
    ingredients: [
      { name: "Chickpeas", amount: 150, unit: "g" },
      { name: "Cucumber", amount: 1, unit: "piece" },
      { name: "Cherry Tomatoes", amount: 100, unit: "g" },
      { name: "Feta Cheese", amount: 50, unit: "g" },
      { name: "Red Onion", amount: 0.25, unit: "piece" },
      { name: "Olive Oil", amount: 2, unit: "tbsp" },
      { name: "Lemon Juice", amount: 1, unit: "tbsp" },
    ],
    instructions: [
      "Rinse and drain chickpeas",
      "Dice cucumber and cherry tomatoes",
      "Thinly slice red onion",
      "Combine all ingredients in a large bowl",
      "Dress with olive oil and lemon juice",
      "Crumble feta cheese on top",
    ],
    nutrition: {
      calories: 320,
      protein: 15,
      carbohydrates: 35,
      fats: 16,
      fiber: 12,
      sugar: 8,
      sodium: 450,
    },
    dietaryTags: ["vegetarian", "mediterranean", "high-fiber"],
    allergens: ["dairy"],
    difficulty: "easy",
    isActive: true,
    averageRating: 4.4,
  },

  // ==================== DINNER MEALS ====================
  {
    name: "Baked Salmon with Roasted Vegetables",
    description: "Omega-3 rich salmon fillet with seasonal roasted vegetables",
    mealType: "dinner",
    imageUrl:
      "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=400&h=300&fit=crop",
    prepTime: 10,
    cookTime: 20,
    servings: 1,
    ingredients: [
      { name: "Salmon Fillet", amount: 180, unit: "g" },
      { name: "Broccoli", amount: 150, unit: "g" },
      { name: "Sweet Potato", amount: 200, unit: "g" },
      { name: "Asparagus", amount: 100, unit: "g" },
      { name: "Olive Oil", amount: 2, unit: "tbsp" },
      { name: "Garlic", amount: 2, unit: "clove" },
      { name: "Lemon", amount: 0.5, unit: "piece" },
    ],
    instructions: [
      "Preheat oven to 400°F (200°C)",
      "Chop vegetables and toss with olive oil",
      "Season salmon with salt, pepper, and garlic",
      "Roast vegetables for 15 minutes",
      "Add salmon and roast for 12-15 minutes",
      "Serve with lemon wedges",
    ],
    nutrition: {
      calories: 480,
      protein: 42,
      carbohydrates: 35,
      fats: 20,
      fiber: 8,
      sugar: 12,
      sodium: 320,
    },
    dietaryTags: ["high-protein", "gluten-free", "omega-3"],
    allergens: ["fish"],
    difficulty: "medium",
    isActive: true,
    averageRating: 4.9,
  },
  {
    name: "Vegetable Stir Fry with Tofu",
    description:
      "Colorful vegetable stir fry with crispy tofu in ginger-soy sauce",
    mealType: "dinner",
    imageUrl:
      "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400&h=300&fit=crop",
    prepTime: 15,
    cookTime: 10,
    servings: 1,
    ingredients: [
      { name: "Firm Tofu", amount: 200, unit: "g" },
      { name: "Broccoli", amount: 100, unit: "g" },
      { name: "Bell Peppers", amount: 1, unit: "piece" },
      { name: "Carrots", amount: 1, unit: "piece" },
      { name: "Soy Sauce", amount: 2, unit: "tbsp" },
      { name: "Ginger", amount: 1, unit: "tbsp" },
      { name: "Sesame Oil", amount: 1, unit: "tbsp" },
    ],
    instructions: [
      "Press and cube tofu, then pan-fry until crispy",
      "Stir-fry vegetables in sesame oil",
      "Add ginger and soy sauce",
      "Combine with tofu and serve hot",
    ],
    nutrition: {
      calories: 320,
      protein: 25,
      carbohydrates: 22,
      fats: 16,
      fiber: 7,
      sugar: 9,
      sodium: 850,
    },
    dietaryTags: ["vegan", "high-protein", "gluten-free"],
    allergens: ["soy"],
    difficulty: "medium",
    isActive: true,
    averageRating: 4.3,
  },

  // ==================== SNACKS ====================
  {
    name: "Apple Slices with Almond Butter",
    description:
      "Crisp apple slices with creamy almond butter for a perfect snack",
    mealType: "snack",
    imageUrl:
      "https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=400&h=300&fit=crop",
    prepTime: 3,
    cookTime: 0,
    servings: 1,
    ingredients: [
      { name: "Apple", amount: 1, unit: "piece" },
      { name: "Almond Butter", amount: 2, unit: "tbsp" },
      { name: "Cinnamon", amount: 0.5, unit: "tsp" },
    ],
    instructions: [
      "Slice apple into wedges",
      "Serve with almond butter for dipping",
      "Sprinkle with cinnamon",
    ],
    nutrition: {
      calories: 210,
      protein: 6,
      carbohydrates: 28,
      fats: 10,
      fiber: 6,
      sugar: 20,
      sodium: 5,
    },
    dietaryTags: ["vegan", "gluten-free", "quick"],
    allergens: ["nuts"],
    difficulty: "easy",
    isActive: true,
    averageRating: 4.6,
  },
  {
    name: "Greek Yogurt with Honey and Walnuts",
    description:
      "Protein-rich Greek yogurt sweetened with honey and crunchy walnuts",
    mealType: "snack",
    imageUrl:
      "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&h=300&fit=crop",
    prepTime: 2,
    cookTime: 0,
    servings: 1,
    ingredients: [
      { name: "Greek Yogurt", amount: 150, unit: "g" },
      { name: "Walnuts", amount: 20, unit: "g" },
      { name: "Honey", amount: 1, unit: "tbsp" },
    ],
    instructions: [
      "Scoop Greek yogurt into a bowl",
      "Top with walnuts and drizzle with honey",
      "Serve immediately",
    ],
    nutrition: {
      calories: 180,
      protein: 18,
      carbohydrates: 15,
      fats: 8,
      fiber: 2,
      sugar: 13,
      sodium: 65,
    },
    dietaryTags: ["high-protein", "vegetarian", "quick"],
    allergens: ["dairy", "nuts"],
    difficulty: "easy",
    isActive: true,
    averageRating: 4.5,
  },
  // Add 15-20 more meals following the same structure...
];

module.exports = { sampleMeals };
