const sampleUsers = [
  {
    name: "John Fitness",
    email: "john.fitness@example.com",
    password: "password123",
    role: "user",
    age: 28,
    gender: "male",
    height: 180,
    currentWeight: 82,
    targetWeight: 75,
    healthGoal: "lose",
    activityLevel: "active",
    dailyCalorieTarget: 2200,
    dietaryPreferences: ["high-protein", "low-carb"],
    allergies: ["shellfish"],
  },
  {
    name: "Sarah Health",
    email: "sarah.health@example.com",
    password: "password123",
    role: "user",
    age: 32,
    gender: "female",
    height: 165,
    currentWeight: 65,
    targetWeight: 60,
    healthGoal: "lose",
    activityLevel: "moderate",
    dailyCalorieTarget: 1800,
    dietaryPreferences: ["vegetarian", "gluten-free"],
    allergies: ["dairy", "gluten"],
  },
  {
    name: "Mike Gains",
    email: "mike.gains@example.com",
    password: "password123",
    role: "user",
    age: 25,
    gender: "male",
    height: 175,
    currentWeight: 70,
    targetWeight: 78,
    healthGoal: "gain",
    activityLevel: "very_active",
    dailyCalorieTarget: 2800,
    dietaryPreferences: ["high-protein", "high-carb"],
    allergies: ["nuts"],
  },
  {
    name: "Admin User",
    email: "admin@dietly.com",
    password: "admin123",
    role: "admin",
    age: 35,
    gender: "male",
    height: 170,
    currentWeight: 75,
    targetWeight: 75,
    healthGoal: "maintain",
    activityLevel: "moderate",
    dailyCalorieTarget: 2400,
    dietaryPreferences: ["balanced"],
    allergies: [],
  },
];

module.exports = { sampleUsers };
